FROM php:8.2-fpm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    nano \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libssl-dev \
    libzip-dev \
    unzip \
    zip \
    && apt-get clean \
    && pecl install redis \
    && docker-php-ext-configure gd \
    && docker-php-ext-configure zip \
    && docker-php-ext-install \
    gd \
    exif \
    opcache \
    pdo_mysql \
    pdo_pgsql \
    pgsql \
    pcntl \
    zip \
    && docker-php-ext-enable redis \
    && rm -rf /var/lib/apt/lists/*;

WORKDIR /var/www

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
# COPY composer.lock composer.json /var/www/

COPY ./v1/ /var/www

RUN composer update

COPY --chown=www:www . /var/www
USER www

# CMD php artisan serve --host=0.0.0.0 --port=8181

EXPOSE 9000
CMD ["php-fpm"]
