version: "3.9"
services:  
  micelios_backend:
    container_name: micelios_backend
    build: 
      context: .
      dockerfile: ./v1/dockerfile
    ports:
      - "8181:8181"
    volumes:
      - ./v1:/usr/src/app
      - ./v1/public:/usr/src/app/public
    depends_on:
      - micelios_bd
    networks:
      - micelios_network
  
  micelios_bd:
    container_name: micelios_bd
    image: mariadb
    restart: always
    volumes:
      - ./v1/storage/db-data:/var/lib/mariadb
    ports: 
      - "3606:3606"
    environment:
      - MARIADB_USER=stickcode
      - MARIADB_PASSWORD=123456
      - MARIADB_ROOT_PASSWORD=12345
      - MARIADB_DATABASE=micelios_db
    networks:
      - micelios_network

networks:
  micelios_network:
    driver: bridge
  